sudo: false
language: python
python:
  - "3.4"
  - "3.6"
addons:
    postgresql: "9.4"
env:
  - DATABASE_USER="postgres" DATABASE_PASSWORD=""
install:
  - pip install pip setuptools six wheel --upgrade
  - pip install -r test_requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create extension hstore;' -U postgres -d template1
  - psql -c 'create database siciarz;' -U postgres
script:
    make test
after_success:
  - coveralls
